const sessions=[
['01','Greetings, Introductions & To Be Verbs','To be verbs'],['02','Family & Pronouns','Pronouns'],['03','Feelings & Interjections','Interjections'],['04','Right Now & Action Verbs','Action verbs'],['05','Likes, Dislikes & Verbs','Verbs'],['06','Daily Routine & Simple Present Tense','Simple Present'],['07','Question Words & Adverbs','Adverbs'],['08','Everyday Objects & Demonstratives','Demonstratives'],['09','Places in a City, Giving Directions & Prepositions','Prepositions'],['10','Making Requests & Polite Modals','Polite modals'],['11','Time & Prepositions','Prepositions of time'],['12','Describing People & Things — Adjectives','Adjectives'],['13','Connecting Ideas & Thoughts — Conjunctions','Conjunctions'],['14','Actions Happening Now — Present Continuous Tense','Present Continuous'],['15','Talking About Past Events — Simple Past Tense','Simple Past'],['16','Describing Past Situations — Past Continuous Tense','Past Continuous'],['17','Recent Actions & Life Experience — Present Perfect Tense','Present Perfect'],['18','Earlier Past Actions — Past Perfect Tense','Past Perfect'],['19','Future Plans & Future Forms','Future forms'],['20','Modal Verbs for Everyday Communication','Modal verbs'],['21','Phrasal Verbs — Speak Naturally','Phrasal verbs'],['22','Classroom / Workplace English Conversation','Practical conversation'],['23','Shopping, Travel & Service English','Practical conversation'],['24','Presentation & Public Speaking — Final Speaking Assessment','Final speaking assessment']];
const common=['I am agree. → I agree.','Myself Ravi. → I’m Ravi. / My name is Ravi.','What is your good name? → What is your name?','He don’t know. → He doesn’t know.','I didn’t went. → I didn’t go.','She have a car. → She has a car.','Discuss about it. → Discuss it.','Explain me. → Explain it to me.','I am having a doubt. → I have a question.','Please revert back. → Please reply / get back to me.'];
const grammar=[['I am a student.','Are you a student?'],['I’m from Madhugiri.','Where are you from?'],['He is my friend.','Who is he?'],['We are classmates.','Are they at school?'],['This is my book.','Those are my classmates.']];
const vocab={
'01':'greeting, introduction, name, surname, hometown, occupation, student, teacher, classmate, welcome, pleasure, meeting, friend, new, ready, happy, morning, afternoon, evening, address',
'02':'family, father, mother, parents, brother, sister, siblings, son, daughter, husband, wife, grandfather, grandmother, uncle, aunt, cousin, relative, children, spouse, member',
'03':'happy, sad, angry, excited, worried, nervous, tired, relaxed, surprised, confused, proud, disappointed, afraid, bored, curious, delighted, concerned, relieved, upset, comfortable',
'04':'walk, run, sit, stand, read, write, speak, listen, open, close, carry, hold, bring, take, clean, cook, draw, sing, dance, study',
'05':'like, dislike, love, enjoy, prefer, hate, mind, avoid, choose, need, want, hope, plan, try, decide, practice, play, watch, read, listen',
'06':'wake up, get up, brush, bathe, dress, eat, drink, go, come, work, study, teach, travel, exercise, cook, clean, rest, sleep, usually, never',
'07':'who, what, when, where, why, how, often, usually, always, never, rarely, quickly, slowly, carefully, loudly, quietly, really, very, quite, extremely',
'08':'pen, pencil, notebook, book, phone, bag, bottle, chair, table, key, wallet, umbrella, watch, computer, charger, door, window, board, this, that',
'09':'bank, hospital, school, station, market, post office, park, hotel, restaurant, pharmacy, temple, bus stop, road, street, bridge, near, next to, opposite, between, behind'};
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo(0,0);if(id==='course')renderSessions();if(id==='quiz')renderQuiz();}
function renderSessions(){const q=(document.getElementById('search')?.value||'').toLowerCase();document.getElementById('sessions').innerHTML=sessions.filter(s=>(s[0]+' '+s[1]+' '+s[2]).toLowerCase().includes(q)).map(s=>`<div class="session" onclick="openSession('${s[0]}')"><span class="num">${s[0]}</span><div style="flex:1"><b>${s[1]}</b><small>${s[2]}</small></div><span class="arrow">›</span></div>`).join('');}
function openSession(n){const s=sessions.find(x=>x[0]===n);const words=(vocab[n]||'20 key vocabulary examples are presented in the textbook.').split(',').map(x=>`<li>${x.trim()}</li>`).join('');document.getElementById('detailContent').innerHTML=`<span class="eyebrow">SESSION ${n}</span><h2>${s[1]}</h2><div class="detailCard"><h3>🎯 Learning Targets</h3><ul><li>Use the session vocabulary in meaningful spoken sentences.</li><li>Choose formal or natural/informal expressions according to context.</li><li>Use the target grammar accurately while speaking.</li><li>Maintain short everyday conversations without reading.</li><li>Identify and correct common spoken-English mistakes.</li></ul></div><div class="detailCard"><h3>📖 20 Key Vocabulary Examples</h3><ol>${words}</ol></div><div class="detailCard"><h3>🗣️ Learn → Practice → Translate → Speak</h3><p><b>Learn:</b> read and understand the examples.</p><p><b>Practice:</b> read aloud → repeat → personalize.</p><p><b>Translate:</b> turn a familiar idea into natural English.</p><p><b>Speak:</b> perform without reading.</p></div><div class="detailCard"><h3>✏️ Grammar Focus: ${s[2]}</h3>${grammar.map(x=>`<div class="example">${x[0]}<br><b>${x[1]}</b></div>`).join('')}</div><div class="detailCard"><h3>💬 Everyday Conversation</h3><div class="example"><b>A:</b> Can you help me with this?<br><b>B:</b> Certainly. Let’s do it.</div><div class="example"><b>A:</b> What do you think?<br><b>B:</b> I think it’s a good idea.</div><div class="example"><b>A:</b> Could you explain that?<br><b>B:</b> Sure. Let me explain.</div><div class="example"><b>A:</b> Are you ready?<br><b>B:</b> Yes, I’m ready.</div></div><div class="detailCard"><h3>⚠️ Common Corrections</h3>${common.map(x=>`<div class="example">${x}</div>`).join('')}</div><div class="detailCard"><h3>✅ Session Review</h3><p>□ I can use the session vocabulary confidently.</p><p>□ I can choose formal or natural expressions appropriately.</p><p>□ I can use the target grammar in speech.</p><p>□ I can maintain a short everyday conversation.</p><p>□ I can identify and correct common mistakes.</p></div>`;showScreen('detail');}
function renderQuiz(){const qs=[['Choose the correct sentence','I agree.','I am agree.'],['Choose the correct sentence','He doesn’t know.','He don’t know.'],['Choose the correct sentence','I didn’t go.','I didn’t went.'],['Choose the correct sentence','She has a car.','She have a car.']];document.getElementById('quizBox').innerHTML=qs.map((q,i)=>`<div class="detailCard"><b>${i+1}. ${q[0]}</b><p><button onclick="this.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);this.textContent='✓ '+this.textContent">${q[1]}</button></p><p><button onclick="this.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);this.textContent='✗ '+this.textContent">${q[2]}</button></p></div>`).join('');}
showScreen('home');
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden');});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;}};
