const titles=["Greetings, Introductions & To Be Verbs","Family & Pronouns","Feelings & Interjections","Right Now & Action Verbs","Likes, Dislikes & Verbs","Daily Routine & Simple Present Tense","Question Words & Adverbs","Everyday Objects & Demonstratives","Places in a City, Giving Directions & Prepositions","Making Requests & Polite Modals","Time & Prepositions","Describing People & Things — Adjectives","Connecting Ideas & Thoughts — Conjunctions","Actions Happening Now — Present Continuous Tense","Talking About Past Events — Simple Past Tense","Describing Past Situations — Past Continuous Tense","Recent Actions & Life Experience — Present Perfect Tense","Earlier Past Actions — Past Perfect Tense","Future Plans & Future Forms","Modal Verbs for Everyday Communication","Phrasal Verbs — Speak Naturally","Classroom / Workplace English Conversation","Shopping, Travel & Service English","Presentation & Public Speaking — Final Speaking Assessment"];
const examples=[
["ನಮಸ್ಕಾರ","Hello."],["ನಿಮ್ಮ ಹೆಸರು ಏನು?","What is your name?"],["ನಾನು ನಾಗೇಂದ್ರ.","I am Nagendra."],["ನೀವು ಹೇಗಿದ್ದೀರಿ?","How are you?"],["ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ.","I am fine."],["ಇದು ನನ್ನ ಕುಟುಂಬ.","This is my family."],["ಅವಳು ನನ್ನ ಸಹೋದರಿ.","She is my sister."],["ನನಗೆ ಸಂತೋಷವಾಗಿದೆ.","I am happy."],["ನಾನು ಈಗ ಓದುತ್ತಿದ್ದೇನೆ.","I am studying now."],["ನನಗೆ ಇಂಗ್ಲಿಷ್ ಇಷ್ಟ.","I like English."],["ನಾನು ಪ್ರತಿದಿನ ಶಾಲೆಗೆ ಹೋಗುತ್ತೇನೆ.","I go to school every day."],["ನೀವು ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತಿದ್ದೀರಿ?","Where are you going?"],["ಇದು ನನ್ನ ಪುಸ್ತಕ.","This is my book."],["ಬ್ಯಾಂಕ್ ಎಲ್ಲಿ ಇದೆ?","Where is the bank?"],["ದಯವಿಟ್ಟು ನನಗೆ ಸಹಾಯ ಮಾಡುತ್ತೀರಾ?","Could you please help me?"],["ಸಮಯ ಎಷ್ಟು?","What time is it?"],["ಅವಳು ಎತ್ತರವಾಗಿದ್ದಾಳೆ.","She is tall."],["ನಾನು ದಣಿದಿದ್ದೇನೆ ಆದರೆ ಸಂತೋಷವಾಗಿದ್ದೇನೆ.","I am tired but happy."],["ನಾನು ನಿನ್ನೆ ಮಾರುಕಟ್ಟೆಗೆ ಹೋದೆ.","I went to the market yesterday."],["ನಾನು ನಾಳೆ ಬರುತ್ತೇನೆ.","I will come tomorrow."]];
function $(s){return document.querySelector(s)}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='sessions')renderSessions()}
function detail(i){$('#detailTitle').textContent=`Session ${i+1}: ${titles[i]}`;$('#detail').classList.add('active');document.querySelectorAll('.screen').forEach(x=>{if(x.id!=='detail')x.classList.remove('active')});renderLesson(i)}
function renderSessions(){const q=($('#sessionSearch')?.value||'').toLowerCase();$('#sessionList').innerHTML=titles.map((t,i)=>({t,i})).filter(x=>x.t.toLowerCase().includes(q)).map(x=>`<div class="session"><div class="num">${x.i+1}</div><div><b>Session ${x.i+1}</b><div class="muted">${x.t}</div></div><button onclick="detail(${x.i})">Open</button></div>`).join('')}
function renderLesson(i){$('#lesson').innerHTML=`<div class="tag">SESSION ${i+1} • 90-DAY MASTER CLASS</div><h2>${titles[i]}</h2><p class="muted">Learn the language pattern, practise aloud, translate, then speak naturally.</p><h3>📖 Learn</h3><p>Study the key vocabulary and grammar idea for this session. Focus on meaning, pronunciation and natural sentence rhythm.</p><h3>🗣️ Practice</h3>${examples.slice(0,5).map(e=>`<div class="card"><b>${e[1]}</b><br><span class="muted">${e[0]}</span><button class="sound" onclick="speakText('${e[1].replace(/'/g,"\\'")}')">🔊</button></div>`).join('')}<h3>📝 Session Review</h3><p>Can you understand the pattern, make your own sentence and speak it without reading?</p>`}
function renderLearn(){const el=$('#learnGrid');el.innerHTML=titles.map((t,i)=>`<button class="tile" onclick="detail(${i})"><span class="tag">SESSION ${i+1}</span><strong>📖 ${t}</strong><span class="muted">Open lesson →</span></button>`).join('')}
function renderPractice(){const el=$('#practiceGrid');el.innerHTML=titles.map((t,i)=>`<div class="card"><b>Session ${i+1}</b><h3>${t}</h3>${examples.slice(i%10,(i%10)+3).map(e=>`<p>Say: <strong>${e[1]}</strong> <button class="sound" onclick="speakText('${e[1].replace(/'/g,"\\'")}')">🔊</button></p>`).join('')}</div>`).join('')}
function renderTranslate(){const el=$('#translateGrid');el.innerHTML=titles.map((t,i)=>`<div class="card"><div class="tag">SESSION ${i+1}</div><h3>${t}</h3>${Array.from({length:20},(_,n)=>{const e=examples[(n+i)%20];return `<div class="card"><b>${n+1}. ${e[0]}</b><button class="mini" onclick="this.nextElementSibling.classList.toggle('show')">Show English</button><div class="answer">${e[1]}</div></div>`}).join('')}</div>`).join('')}
function renderSpeak(){const el=$('#speakGrid');el.innerHTML=titles.map((t,i)=>`<div class="card"><div class="tag">SESSION ${i+1}</div><h3>💬 ${t}</h3><div class="chatWrap">${Array.from({length:20},(_,n)=>{const e=examples[(n+i)%20],b=n%2===1;return `<div class="chat ${b?'b':''}"><div class="bubble"><small>Student ${b?'B':'A'}</small>${e[1]} <button class="sound" onclick="speakText('${e[1].replace(/'/g,"\\'")}')">🔊</button></div></div>`}).join('')}</div></div>`).join('')}
function renderQuiz(){const el=$('#quizGrid');el.innerHTML=titles.map((t,i)=>`<div class="quizCard"><div class="tag">SESSION ${i+1}</div><h3>📝 ${t}</h3>${Array.from({length:10},(_,n)=>{const e=examples[(n+i)%20],level=n<3?'Easy':n<7?'Medium':'Difficult';return `<div class="card"><b>${n+1}. ${level}</b><p>Choose the best English sentence for:</p><strong>${e[0]}</strong><button class="opt" onclick="checkQuiz(this,true)">${e[1]}</button><button class="opt" onclick="checkQuiz(this,false)">I am going market yesterday.</button><div class="muted result"></div></div>`}).join('')}</div>`).join('')}
function checkQuiz(btn,ok){btn.parentElement.querySelectorAll('.opt').forEach(x=>x.disabled=true);btn.classList.add(ok?'correct':'wrong');btn.parentElement.querySelector('.result').textContent=ok?'✓ Correct!':'✗ Try again and review the sentence.'}
function speakText(text){if('speechSynthesis' in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
function pick(i){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#home').classList.add('active');detail(i)}
$('#sessionSearch')?.addEventListener('input',renderSessions);renderLearn();renderPractice();renderTranslate();renderSpeak();renderQuiz();go('home');